name: Ping API Every Minute

on:
  schedule:
    - cron: '*/1 * * * *' 
  workflow_dispatch:  

jobs:
  ping_api:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar requisição HTTP para API
        run: |
          curl -f -X GET https://mastria-agenda.onrender.com/ping || exit 1
          # -f (fail silently) faz com que o comando falhe caso haja erro na requisição.
